library:
  source-dirs: src
  exposed-modules:
  - Checkout
  - ShoppingCart
  - Types
  - Api
tests:
  ad-pricer-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wall
    - -with-rtsopts=-N
    dependencies:
    - ad-pricer
    - hspec
    - QuickCheck
copyright: 2018 Author name here
maintainer: example@example.com
dependencies:
- bytestring
- base >= 4.7 && < 5
- aeson >= 1.4.1.0
- text
- containers
- raw-strings-qq >= 1.1
- servant == 0.14.1
- servant-server
- wai
- warp
name: ad-pricer
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/ad-pricer
license: BSD3
executables:
  ad-pricer-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wall
    - -with-rtsopts=-N
    dependencies:
    - ad-pricer
description: Please see the README on GitHub at <https://github.com/githubuser/ad-pricer#readme>
